matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.1
      env:
        - OS=ios

    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-26.0.2
          - android-21
          - android-26
          - sys-img-armeabi-v7a-android-21
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      env:
        - OS=android

script: node_modules/tipsi-travis-scripts/scripts/travis.sh
