matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.1
      env:
        - OS: 'ios'

    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-26.0.2
          - android-21
          - android-26
          - sys-img-armeabi-v7a-android-21
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      env:
        - OS: 'android'

script:
  # See https://austinpray.com/ops/2015/09/20/change-travis-node-version.html

  # Clear out whatever version of NVM Travis has.
  # Their version of NVM is probably old.
  - rm -rf ~/.nvm

  # Grab NVM.
  - git clone https://github.com/creationix/nvm.git ~/.nvm

  # Checkout the latest stable tag.
  # Note that you can just hardcode a preferred version here.

  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)

  # Install the desired version of Node
  - source ~/.nvm/nvm.sh

  - nvm install --lts

  - npm run ci

